#!/usr/bin/env python
# coding: utf-8

"""
WhatIsThisHere

Created: 09.05.20
"""

import json
import sys
from pathlib import Path
import feedparser
import requests
from luechenbresse import data


if __name__ == "__main__":
    feeds = data.feeds()
    liste = [ f for f in feeds ]
    for i, f in enumerate(liste):
        print(f"{i:6d}. {f}")
    try:
        i = int(input("Such dir einen aus: "))
    except ValueError:
        raise SystemExit(0)
    print(liste[i])
    feed_name = liste[i]
    url = feeds[feed_name]["feed"]

    r = requests.get(url)
    print(f"GET {url}: HTTP {r.status_code}")
    xml_path = Path("muster") / (feed_name + ".xml")
    with xml_path.open(mode="w") as f:
        f.write(r.text)
    print(f"Feed-Source in {xml_path}")

    fd = feedparser.parse(r.text)
    file_content = json.dumps(fd, indent=4)
    json_path = Path("muster") / (feed_name + ".json")
    with json_path.open(mode="w") as f:
        f.write(file_content)
    print(f"geparster Feed in {json_path}")

