#!/usr/bin/env python
# coding: utf-8

"""
WhatIsThisHere

Created: 09.05.20
"""

import json
import sys
import feedparser
import requests
from luechenbresse import data


if __name__ == "__main__":
    feeds = data.feeds()
    liste = [ f for f in feeds ]
    for i, f in enumerate(liste):
        print(f"{i:6d}. {f}")
    try:
        i = int(input("Such dir einen aus: "))
    except ValueError:
        raise SystemExit(0)
    print(liste[i])
    feed_name = liste[i]
    url = feeds[feed_name]["feed"]

    r = requests.get(url)
    print(f"GET {url}: HTTP {r.status_code}")
    with open("./muster/"+feed_name+".xml", "w") as f: # TODO würg...
        f.write(r.text)

    fd = feedparser.parse(url)
    file_content = json.dumps(fd, indent=4)
    lines = file_content.split("\n")
    for line in lines[:20]:
        print(line)
    with open("./muster/"+feed_name+".json", "w") as f: # TODO würg...
        f.write(file_content)

