#!/usr/bin/env python
# coding: utf-8

"""
WhatIsThisHere

Created: 09.05.20
"""

import json
import sys
import feedparser
from luechenbresse import data


if __name__ == "__main__":
    feeds = data.feeds()
    liste = [ f for f in feeds ]
    for i, f in enumerate(liste):
        print(f"{i:6d}. {f}")
    try:
        i = int(input("Such dir einen aus: "))
    except ValueError:
        raise SystemExit(0)
    print(liste[i])
    feed_name = liste[i]
    fd = feedparser.parse(feeds[feed_name]["feed"])
    file_content = json.dumps(fd, indent=4)
    lines = file_content.split("\n")
    for line in lines[:20]:
        print(line)
    with open("./muster/"+feed_name+".json", "w") as f: # TODO würg...
        f.write(file_content)